### ISSUE TITLE
ErrorWithCause: Error Uploading Files

### ISSUE THREAD

**Issue by yunkillable** [professorsugoi/Deploy-Astro-Neocities#1]
I've been attempting to deploy with this code but I get the following feedback:
```ErrorWithCause: Error uploading files
    at NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1.1.18/dist/index.js:20677:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1.1.18/dist/index.js:22489:17)
caused by: JSONHTTPError: Bad Request
    at handleResponse (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1.1.18/dist/index.js:2246:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1.1.18/dist/index.js:20675:11)```

**Comment by professorsugoi** [comment]
i just updated the repo, but it looks like outdated code wasnt the issue.  
where is your `dist` folder? an updated version is built each time during `npm run build`.  
you may also need to try a new API key, or double check that the github workflow tab has permissions to run actions.  

hopefully one of these helps

**Comment by yunkillable** [comment]
That was it! Thank you for the help!
